### ISSUE TITLE
Add activity "homebuyer"

### ISSUE THREAD

**Issue by vaibhav899050** [vaibhav899050/Shopping-Application#1]

**Comment by sidling1** [comment]
I want to work on this

**Comment by prvn2004** [comment]
can you assign this to me?

**Comment by prvn2004** [comment]
i have raised a PR. please check

**Comment by vaibhav899050** [comment]
can you please change the directory of the homebuyer.kt file. I have the rasised the issue.

**Comment by vaibhav899050** [comment]
The android manifest file is showing error because of that

**Comment by vaibhav899050** [comment]
no problem I fixed those issues
