### ISSUE TITLE
add login form in the main activity

### ISSUE THREAD

**Issue by vaibhav899050** [vaibhav899050/Shopping-Application#4]
textbox 1 - username
textbox 2 - password

**Comment by ashutoshdhamaniya** [comment]
I want to work on this issue

**Comment by ashutoshdhamaniya** [comment]
I have added the login form. Please review it.

**Comment by vaibhav899050** [comment]
great work Ashutosh!
just do one thing please remove master from the android manifest file.
I have raised the issue. Please look into it.

**Comment by vaibhav899050** [comment]
"master" *

**Comment by vaibhav899050** [comment]
No problem I fixed those issues
